### ISSUE TITLE
Sign in Problem

### ISSUE THREAD

**Issue by JamesRawal456** [JamesRawal456/TourismManagementSystem#7]
The username and password is correct but still i cannot sign in as a user
even atfter signing in the same page is displayed
![hhhhhhhh](https://user-images.githubusercontent.com/101965640/168428381-9083ef92-1660-48c8-b027-c0db0077857a.png)

**Comment by nurusherpa** [comment]
In line number 8 replace "dbh " keyword with "con" then it will work.
![1](https://user-images.githubusercontent.com/101965715/168428564-53a04ef1-455f-4516-b3ae-384947c17990.PNG)
