### ISSUE TITLE
detail button not working

### ISSUE THREAD

**Issue by nurusherpa** [JamesRawal456/TourismManagementSystem#8]
when I clicked on detail button in package detail page it doesn"t respond and i get the following interface.
![1](https://user-images.githubusercontent.com/101965715/168428950-805aa3d7-c371-413f-b358-bf004c32f6f6.PNG)

**Comment by JamesRawal456** [comment]
Go to package-details page and in line number 68, do the following changes as I have done in the picture below
![ueueueue](https://user-images.githubusercontent.com/101965640/168429132-2bbf6fa4-063b-4c08-97a2-1bb7ec3348ad.png)
