### ISSUE TITLE
Enquiry form not working

### ISSUE THREAD

**Issue by JamesRawal456** [JamesRawal456/TourismManagementSystem#9]
When Submit button is pressed in enquiry page it doesn't work. White screen is shown.
![jins](https://user-images.githubusercontent.com/101965640/168475181-43d5eb05-b666-426b-bd2c-ad737656bb3b.png)

**Comment by bipinsu** [comment]
In line no 13 and 20 replace "dbh" keyword with "con" keyword. 
![issue](https://user-images.githubusercontent.com/101965768/168475370-a992cacf-6e81-4353-bb51-3a922ed6dca9.png)
